from login_page import *
from professor_dashboard_page import *
from student_dashboard_page import *
from create_class_page import *
from add_student_class_page import *
from class_page import *
from add_online_test_page import *
from generator_page import *
from test_modify_page import *
from generated_questions_page import *
